# Use the latest Ubuntu as the base image
FROM ubuntu:latest
# Update APT repositories
RUN apt-get update
# Upgrade currently installed software through APT
RUN apt-get upgrade -y
# Run a command when the container starts to echo "Hello, World!"
CMD ["echo", "Hello, World!"]